### ISSUE TITLE
Pivot Partitioning: richtige Lösung falsch korrigiert

### ISSUE THREAD

**Issue by mikejdoe** [hydranox/foo-pub#227]
![screen shot 2015-06-18 at 14 42 25](https://cloud.githubusercontent.com/assets/12952079/8231372/519dc4b4-15c8-11e5-8d6b-ac3b75db9806.png)
![screen shot 2015-06-18 at 14 43 48](https://cloud.githubusercontent.com/assets/12952079/8231391/7b9afdae-15c8-11e5-9535-322b5b20dc16.png)

**Comment by alexanderj1988** [comment]
ich sehe keinen Fehler, daher geschlossen

**Comment by mikejdoe** [comment]
Die -7 darf nicht an den 2. Index getauscht werden. Oder sehe ich da was falsch?

**Comment by alexanderj1988** [comment]
natürlich... schaut euch doch bitte die spezifikation im wiki an...
Otherwise (that is, ):   
   - Swap  and .

nach iteration 2 befindet sich der pointer i1 auf index 2 und S[2]=6 und 6 > -7 => swap(i1,i3) = swap(2,12) => S[2] = -7 und S[12] = 6
... 



     mikejdoe <notifications@github.com> schrieb am 14:56 Donnerstag, 18.Juni 2015:
   

 Die -7 darf nicht an den 2. Index getauscht werden. Oder sehe ich da was falsch?—
